In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3]) # Vector
b = np.array([4,5,6,7]) # Vector
c = np.array([
    [0,1,2,3],
    [4,5,6,7]
    ]) # Matrix
d = np.zeros((2,4)) # 2x4 Matrix of zeros
e = np.random.rand(2,5) # 2x5 Matrix of random numbers(from 0 to 1)

In [ ]:
print(a) #
print(b) #
print(c) #
print(d) #
print(e) #

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.92583904 0.80858835 0.56491371 0.8051217  0.68514322]
 [0.8148101  0.29626851 0.69095609 0.1699129  0.34733043]]


In [8]:
print(a * 0.1)
print(a * b) # Element-wise multiplication
print(a * c) # Element-wise multiplication
# print(a * e)

[0.  0.1 0.2 0.3]
[ 0  5 12 21]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [12]:
a = np.zeros((1,4))
b = np.zeros((4,3))
c = a.dot(b) # Dot product
print(c)
print(c.shape) # (1,3)

[[0. 0. 0.]]
(1, 3)


In [13]:
a = np.zeros((2,4))
b = np.zeros((4,3))
c = a.dot(b) # Dot product
print(c.shape) # (2,3)

(2, 3)


In [14]:
e = np.zeros((2,1))
f = np.zeros((1,3))
g = e.dot(f) # Dot product
print(g.shape) # (2,3)

(2, 3)


In [ ]:
h = np.zeros((5,4)).T # Transpose of a 5x4 matrix, resulting in a 4x5 matrix
print(h.shape) # (4,5)

i = np.zeros((5,6))
j = h.dot(i) # Dot product of a 4x5 and 5x6 matrix, resulting in a 4x6 matrix
print(j.shape) # (4,6)

(4, 5)
(4, 6)


In [18]:
h = np.zeros((5,4))
i = np.zeros((5,6))
j = h.T.dot(i) # Dot product of a 4x5 and 5x6 matrix, resulting in a 4x6 matrix
print(j.shape) # (4,6)

(4, 6)
