In [9]:
!pip install numpy

In [10]:
import numpy as np

np.random.seed(1)

# この関数は負数をすべて０に設定する
def relu(x):
    return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array(
    [
        [1, 0, 1],
        [0, 1, 1],
        [0, 0, 1],
        [1, 1, 1]
    ]
)

walk_vs_stop = np.array(
    [
        [1, 1, 0, 0]
    ]
).T

# （ランダムに初期化された）３つの層を結合するために２つの重みセットを使用
weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

print("streetlights:\n", streetlights)
print("walk_vs_stop:\n", walk_vs_stop)

print("weights_0_1:\n", weights_0_1)
print("weights_1_2:\n", weights_1_2)

streetlights:
 [[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
walk_vs_stop:
 [[1]
 [1]
 [0]
 [0]]
weights_0_1:
 [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
weights_1_2:
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [11]:
layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
# layer_1の出力がRELUに渡され、負の値が０になり、次の層であるLayer_2の入力になる
layer_2 = np.dot(layer_1, weights_1_2)

print("layer_0:\n", layer_0)
print("layer_1:\n", layer_1)
print("layer_2:\n", layer_2)


layer_0:
 [1 0 1]
layer_1:
 [-0.          0.51828245 -0.         -0.        ]
layer_2:
 [0.39194327]
