In [41]:
!pip install numpy

In [42]:
import numpy as np

np.random.seed(1)

# X > 0 の場合はXを返し、それ以外の場合は０を返す
def relu(x):
    return (x > 0) * x

# output > 0 の場合は1を返し、それ以外の場合は０を返す
# relu関数の微分係数
def relu2deriv(output):
    return output > 0

alpha = 0.2
hidden_size = 4

streetlights = np.array(
    [
        [1, 0, 1],
        [0, 1, 1],
        [0, 0, 1],
        [1, 1, 1]
    ]
)

walk_vs_stop = np.array(
    [
        [1, 1, 0, 0]
    ]
).T


# （ランダムに初期化された）３つの層を結合するために２つの重みセットを使用
weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

print("streetlights:\n", streetlights)
print("walk_vs_stop:\n", walk_vs_stop)

print("weights_0_1:\n", weights_0_1)
print("weights_1_2:\n", weights_1_2)

streetlights:
 [[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
walk_vs_stop:
 [[1]
 [1]
 [0]
 [0]]
weights_0_1:
 [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
weights_1_2:
 [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]


In [ ]:
for iteration in range(60):
    layer_2_error = 0

    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i + 1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)

        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i + 1]) ** 2)
        # prediction - goal_prediction
        layer_2_delta = (layer_2 - walk_vs_stop[i:i + 1])

        # layer_2_deltaにweights_1_2をかけることで、
        # layer_2_deltaに基づいてlayer_1_deltaを求める
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)

        #print("-----Iteration:", iteration)
        #print(f"layer_0({layer_0.shape}):\n", layer_0)
        #print(f"layer_1({layer_1.shape}):\n", layer_1)
        #print(f"layer_2({layer_2.shape}):\n", layer_2)
        #print(f"layer_2_error({layer_2_error.shape}):\n", layer_2_error)
        #print(f"layer_2_delta({layer_2_delta.shape}):\n", layer_2_delta)
        #print(f"layer_1_delta({layer_1_delta.shape}):\n", layer_1_delta)

        # layer_1.T.dot(layer_2_delta)は、layer_1の各ニューロンの出力がlayer_2_deltaにどの程度影響を与えたかを示す勾配を計算する
        weights_1_2_delta = layer_1.T.dot(layer_2_delta)
        # weights += layer_1の出力値 * delta(layer_2)
        weights_1_2 = weights_1_2 - alpha * weights_1_2_delta

        weights_0_1_delta = layer_0.T.dot(layer_1_delta)
        # weights += layer_0のINPUT値 * delta(layer_1)
        weights_0_1 = weights_0_1 - alpha * weights_0_1_delta

        #print(f"weights_0_1({weights_0_1.shape}):\n", weights_0_1)
        #print(f"weights_1_2({weights_1_2.shape}):\n", weights_1_2)

    if (iteration % 10 == 9):
        print("Error:" + str(layer_2_error))


Error:0.6342311598444467
Error:0.35838407676317513
Error:0.0830183113303298
Error:0.006467054957103705
Error:0.0003292669000750734
Error:1.5055622665134859e-05
