In [5]:
!pip install numpy

In [10]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x # returns x if x > 0
                       # return 0 otherwise

def relu2deriv(output):
    return output>0 # returns 1 for input > 0
                    # return 0 otherwise

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

print(f"weights_0_1{weights_0_1.shape,type(weights_0_1)}=\n" + str(weights_0_1))
print(f"weights_1_2{weights_1_2.shape,type(weights_1_2)}=\n" + str(weights_1_2))

for iteration in range(1):
   layer_2_error = 0
   for i in range(len(streetlights)):
      print(f"i={i}")
      layer_0 = streetlights[i:i+1]
      layer_1 = relu(np.dot(layer_0,weights_0_1))
      layer_2 = np.dot(layer_1,weights_1_2)

      print(f"layer_0{layer_0.shape,type(layer_0)}=\n" + str(layer_0))
      print(f"layer_1{layer_1.shape,type(layer_1)}=\n" + str(layer_1))
      print(f"layer_2{layer_2.shape,type(layer_2)}=\n" + str(layer_2))


      layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)

      layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
      layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
      print(f"layer_2_delta{layer_2_delta.shape,type(layer_2_delta)}=\n" + str(layer_2_delta))
      print(f"layer_1_delta{layer_1_delta.shape,type(layer_1_delta)}=\n" + str(layer_1_delta))

      print("layer_1.T.dot(layer_2_delta)=\n" + str(layer_1.T.dot(layer_2_delta)))
      print("layer_0.T.dot(layer_1_delta)=\n" + str(layer_0.T.dot(layer_1_delta)))
      print("layer_0.T=\n" + str(layer_0.T))

      weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
      weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)

   if(iteration % 10 == 9):
      print("Error:" + str(layer_2_error))

weights_0_1((3, 4), <class 'numpy.ndarray'>)=
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
weights_1_2((4, 1), <class 'numpy.ndarray'>)=
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
i=0
layer_0((1, 3), <class 'numpy.ndarray'>)=
[[1 0 1]]
layer_1((1, 4), <class 'numpy.ndarray'>)=
[[-0.          0.51828245 -0.         -0.        ]]
layer_2((1, 1), <class 'numpy.ndarray'>)=
[[0.39194327]]
layer_2_delta((1, 1), <class 'numpy.ndarray'>)=
[[-0.60805673]]
layer_1_delta((1, 4), <class 'numpy.ndarray'>)=
[[ 0.         -0.45983371  0.         -0.        ]]
layer_1.T.dot(layer_2_delta)=
[[ 0.        ]
 [-0.31514514]
 [ 0.        ]
 [ 0.        ]]
layer_0.T.dot(layer_1_delta)=
[[ 0.         -0.45983371  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.45983371  0.         -0.        ]]
layer_0.T=
[[1]
 [0]
 [1]]
i=1
layer_0((1, 3), 