# 複数の入力と出力を持つ勾配降下法
https://github.com/iamtrask/Grokking-Deep-Learning/blob/master/Chapter5%20-%20Generalizing%20Gradient%20Descent%20-%20Learning%20Multiple%20Weights%20at%20a%20Time.ipynb


In [2]:
!pip install numpy

In [ ]:
import numpy as np

weights = np.array([
    # toes,wlrec,nfans
    [0.1, 0.1, -0.3], # hurt?
    [0.1, 0.2, 0.0],  # win?
    [0.0, 1.3, 0.1]   # sad?
])

# Input data
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# goal predictions
hurt = [0.1, 0.0, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

alpha = 0.01

input = np.array([toes[0], wlrec[0], nfans[0]])
goal_pred = np.array([hurt[0], win[0], sad[0]])

# Inference
pred = np.dot(input, weights.T)
print("input=" + str(input))
print("weights=" + str(weights))
print("pred=" + str(pred))

error = (pred - goal_pred) ** 2
print("error=" + str(error))

delta = pred - goal_pred
print("delta=" + str(delta))

# 微分係数：3x3 matrix
# 各要素は、各weightsの要素に対する誤差の変化率を表す
derivative = np.outer(delta, input)
print("derivative=" + str(derivative))

# update weights
weights = weights - alpha * derivative
print("weights=" + str(weights))

input=[8.5  0.65 1.2 ]
weights=[[ 0.1  0.1 -0.3]
 [ 0.1  0.2  0. ]
 [ 0.   1.3  0.1]]
pred=[0.555 0.98  0.965]
error=[2.07025e-01 4.00000e-04 7.48225e-01]
delta=[ 0.455 -0.02   0.865]
derivative=[[ 3.8675   0.29575  0.546  ]
 [-0.17    -0.013   -0.024  ]
 [ 7.3525   0.56225  1.038  ]]
weights=[[ 6.1325000e-02  9.7042500e-02 -3.0546000e-01]
 [ 1.0170000e-01  2.0013000e-01  2.4000000e-04]
 [-7.3525000e-02  1.2943775e+00  8.9620000e-02]]
