In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
output = np.dot(3, [1, 2, 3])
print(output)
np.dot([1, 2, 3], 3)
print(output)

output = np.dot([1, 2, 3], [4, 5, 6])
print(output)

# np.array([1]).dot(np.array([4, 5, 6]))

[3 6 9]
[3 6 9]
32


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a * b # 各要素ごとに掛け算する
c

array([ 4, 10, 18])

In [7]:
c = a.dot(b) # 内積を計算する
c

np.int64(32)

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(f"a({a.shape})=\n{a}")
print(f"b({b.shape})=\n{b}")
c = a.dot(b)
c

a((2, 3))=
[[1 2 3]
 [4 5 6]]
b((3, 2))=
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])