In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
output = np.dot(3, [1, 2, 3])
print(output)
np.dot([1, 2, 3], 3)
print(output)

output = np.dot([1, 2, 3], [4, 5, 6])
print(output)

# np.array([1]).dot(np.array([4, 5, 6]))

[3 6 9]
[3 6 9]
32


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a * b # 各要素ごとに掛け算する
c

array([ 4, 10, 18])

In [7]:
c = a.dot(b) # 内積を計算する
c

np.int64(32)

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
print(f"a({a.shape})=\n{a}")
print(f"b({b.shape})=\n{b}")
c = a.dot(b)
c

a((2, 3))=
[[1 2 3]
 [4 5 6]]
b((3, 2))=
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])

In [5]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5,6,7])

x = np.outer(a,b)
y = np.outer(a.T,b)

print(f"x({x.shape})=\n{x}")
print(f"y({y.shape})=\n{y}")

x((4, 3))=
[[ 5  6  7]
 [10 12 14]
 [15 18 21]
 [20 24 28]]
y((4, 3))=
[[ 5  6  7]
 [10 12 14]
 [15 18 21]
 [20 24 28]]


In [ ]:
import numpy as np

# layer: 1x4 matrix
layer = np.array([[0.0,0.51828245,0.0,0.0]])
print(f"layer({layer.shape})=\n{layer}")

# delta: 1x4 matrix
delta = np.array([[ 0.0, -0.45983371,0.0,0.0]])
print(f"delta({delta.shape})=\n{delta}")

# layer.T: 4x1 matrix
print(f"layer.T({layer.T.shape})=\n{layer.T}")

# 4x1 matrix x 1x4 matrix = 4x4 matrix
derivative = layer.T.dot(delta)
print(f"derivative({derivative.shape})=\n{derivative}")





layer((1, 4))=
[[0.         0.51828245 0.         0.        ]]
delta((1, 4))=
[[ 0.         -0.45983371  0.          0.        ]]
layer.T((4, 1))=
[[0.        ]
 [0.51828245]
 [0.        ]
 [0.        ]]
derivative((4, 4))=
[[ 0.          0.          0.          0.        ]
 [ 0.         -0.23832374  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [17]:
import numpy as np

# input: 1x3 matrix
input = np.array([[1,0,1]])
# delta: 1x4 matrix
delta = np.array([[0.0, -0.45983371,0.0,0.0]])

input.T @ delta

array([[ 0.        , -0.45983371,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.45983371,  0.        ,  0.        ]])

In [20]:
import numpy as np

input = np.array([1,0,1]).reshape(1,3)
input

array([[1, 0, 1]])

In [21]:
import numpy as np

input = np.array([1,0,1])
delta = np.array([0.0, -0.45983371,0.0,0.0])

np.outer(input, delta)

array([[ 0.        , -0.45983371,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ],
       [ 0.        , -0.45983371,  0.        ,  0.        ]])

In [22]:
import numpy as np

input = np.array([1,0,1])
delta = np.array([0.0, -0.45983371,0.0,0.0])

np.outer(input.T, delta)

array([[ 0.        , -0.45983371,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ],
       [ 0.        , -0.45983371,  0.        ,  0.        ]])